const std = @import("std");
const Allocator = std.mem.Allocator;

const spec_test_options = @import("spec_test_options");

pub fn main(init: std.process.Init) !void {
    const allocator = std.heap.smp_allocator;
    const io = init.io;
    const tests = &[_][]const u8{
        "general",
        "minimal",
        "mainnet",
    };
    try write_version(io);
    for (tests) |test_name| {
        try download_and_extract_spec_test(
            allocator,
            io,
            spec_test_options.spec_test_url,
            spec_test_options.spec_test_version,
            test_name,
            spec_test_options.spec_test_out_dir,
        );
    }
}

fn write_version(io: std.Io) !void {
    const version_file = try std.Io.Dir.createFile(.cwd(), io, "test/spec/version.txt", .{});
    defer version_file.close(io);

    var write_buf: [4 * 1024]u8 = undefined;
    var writer = version_file.writer(io, &write_buf);
    try writer.interface.print(
        \\// This file is generated by download_spec_tests.zig.
        \\// This file exists as a cache key for the spec tests in CI.
        \\// Do not commit changes by hand.
        \\
        \\{s}
        \\
    , .{spec_test_options.spec_test_version});
    try writer.end();
}

fn download_and_extract_spec_test(
    allocator: Allocator,
    io: std.Io,
    spec_test_url: []const u8,
    spec_test_version: []const u8,
    test_name: []const u8,
    out_dir: []const u8,
) !void {
    try download_spec_test_archive(allocator, io, spec_test_url, spec_test_version, test_name, out_dir);
    try extract_spec_test_archive(allocator, io, spec_test_version, test_name, out_dir);
}

fn download_spec_test_archive(
    allocator: Allocator,
    io: std.Io,
    spec_test_url: []const u8,
    spec_test_version: []const u8,
    test_name: []const u8,
    out_dir: []const u8,
) !void {
    const filename = try std.fmt.allocPrint(allocator, "{s}.tar.gz", .{test_name});
    defer allocator.free(filename);

    const archive_dirname = try std.fs.path.join(allocator, &[_][]const u8{ out_dir, spec_test_version });
    defer allocator.free(archive_dirname);

    std.Io.Dir.createDirPath(.cwd(), io, archive_dirname) catch |err| switch (err) {
        error.PathAlreadyExists => {},
        else => return err,
    };
    const archive_dir = try std.Io.Dir.openDir(.cwd(), io, archive_dirname, .{});

    const already_downloaded = archive_dir.openFile(io, filename, .{}) catch null;
    if (already_downloaded != null) {
        std.log.info("already downloaded {s}", .{filename});
        already_downloaded.?.close(io);
        return;
    }

    var file = try archive_dir.createFile(io, filename, .{});
    defer file.close(io);

    std.log.info("downloading spec test {s} {s}", .{ spec_test_version, test_name });

    var client: std.http.Client = .{ .allocator = allocator, .io = io };
    defer client.deinit();

    const url = try std.fmt.allocPrint(
        allocator,
        "{s}/releases/download/{s}/{s}.tar.gz",
        .{
            spec_test_url,
            spec_test_version,
            test_name,
        },
    );
    defer allocator.free(url);

    std.log.info("spec test url: {s}", .{url});

    const uri = try std.Uri.parse(url);

    var req = try client.request(.GET, uri, .{});
    defer req.deinit();

    std.log.info("sending request", .{});
    try req.sendBodiless();

    var redirect_buffer: [8 * 1024]u8 = undefined;
    var response = try req.receiveHead(&redirect_buffer);

    // write to disk
    std.log.info("writing response to disk - {s}", .{filename});

    var write_buf: [16 * 1024]u8 = undefined;
    var file_writer = file.writer(io, &write_buf);
    var body_reader = response.reader(&.{});
    const bytes_count = body_reader.streamRemaining(&file_writer.interface) catch |err| switch (err) {
        error.ReadFailed => return response.bodyErr().?,
        else => |e| return e,
    };
    try file_writer.flush();
    std.log.info("response written to disk - {d} bytes", .{bytes_count});
}

fn extract_spec_test_archive(
    allocator: Allocator,
    io: std.Io,
    spec_test_version: []const u8,
    test_name: []const u8,
    out_dir: []const u8,
) !void {
    const archive_dirname = try std.fs.path.join(allocator, &[_][]const u8{ out_dir, spec_test_version });
    defer allocator.free(archive_dirname);

    const filename = try std.fmt.allocPrint(allocator, "{s}.tar.gz", .{test_name});
    defer allocator.free(filename);

    var archive_dir = try std.Io.Dir.openDir(.cwd(), io, archive_dirname, .{});
    defer archive_dir.close(io);

    var already_extracted = archive_dir.openDir(io, test_name, .{});
    if (already_extracted) |*a| {
        defer a.close(io);
        std.log.info("already extracted {s}", .{filename});
        return;
    } else |err| {
        if (err != error.FileNotFound) {
            return err;
        }
    }

    const archive_file = try archive_dir.openFile(io, filename, .{});
    defer archive_file.close(io);

    archive_dir.createDir(io, test_name, .default_dir) catch |err| switch (err) {
        error.PathAlreadyExists => {},
        else => return err,
    };
    const extracted_out = try archive_dir.openDir(io, test_name, .{});

    var read_buf: [16 * 1024]u8 = undefined;
    var file_reader = archive_file.reader(io, &read_buf);

    var decompress_buf: [std.compress.flate.max_window_len]u8 = undefined;
    var decompressor = std.compress.flate.Decompress.init(&file_reader.interface, .gzip, &decompress_buf);

    std.log.info("extracting {s}", .{filename});

    try std.tar.pipeToFileSystem(io, extracted_out, &decompressor.reader, .{});
    std.log.info("extract {s} complete", .{filename});
}
